<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use App\Models\ProductType;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Supprimer tous les produits existants
        $this->command->info('🗑️  Suppression de tous les produits existants...');
        
        // Désactiver temporairement les contraintes de clé étrangère
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('products')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        
        $this->command->info('✅ Tous les produits ont été supprimés.');

        // Récupérer les catégories et types de produits
        $categories = Category::all();
        $productTypes = ProductType::all();

        if ($categories->isEmpty() || $productTypes->isEmpty()) {
            $this->command->error('❌ Veuillez d\'abord exécuter CategorySeeder et ProductTypeSeeder !');
            return;
        }

        // Trouver ou créer les catégories nécessaires
        $phoneCategory = Category::where('name', 'LIKE', '%téléphone%')
            ->orWhere('name', 'LIKE', '%phone%')
            ->orWhere('name', 'LIKE', '%smartphone%')
            ->first() ?? $categories->first();

        $accessoryCategory = Category::where('name', 'LIKE', '%accessoire%')
            ->orWhere('name', 'LIKE', '%accessory%')
            ->first() ?? $categories->first();

        // Trouver les types de produits
        $phoneType = $productTypes->firstWhere('name', 'LIKE', '%téléphone%')
            ?? $productTypes->firstWhere('name', 'LIKE', '%phone%')
            ?? $productTypes->first();

        $accessoryType = $productTypes->firstWhere('name', 'LIKE', '%accessoire%')
            ?? $productTypes->firstWhere('name', 'LIKE', '%accessory%')
            ?? $productTypes->last();

        $this->command->info('📱 Création des produits de test pour le filtrage...');

        // ============================================
        // PRODUITS TÉLÉPHONES
        // ============================================
        $phones = [
            // Tecno
            [
                'name' => 'Tecno Spark 20 Pro',
                'description' => 'Smartphone Tecno Spark 20 Pro avec écran 6.78" et 8GB RAM',
                'price' => 95000,
                'cost_price' => 75000,
                'stock_quantity' => 25,
                'min_stock_alert' => 5,
                'brand' => 'Tecno',
                'range' => 'Spark',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'Tecno Camon 20 Pro',
                'description' => 'Tecno Camon 20 Pro avec caméra 64MP et processeur Helio G99',
                'price' => 125000,
                'cost_price' => 100000,
                'stock_quantity' => 18,
                'min_stock_alert' => 3,
                'brand' => 'Tecno',
                'range' => 'Camon',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'Tecno Phantom X2',
                'description' => 'Tecno Phantom X2 haut de gamme avec écran AMOLED',
                'price' => 180000,
                'cost_price' => 150000,
                'stock_quantity' => 10,
                'min_stock_alert' => 2,
                'brand' => 'Tecno',
                'range' => 'Phantom',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'Tecno Pop 8',
                'description' => 'Tecno Pop 8 entrée de gamme avec Android Go',
                'price' => 55000,
                'cost_price' => 40000,
                'stock_quantity' => 35,
                'min_stock_alert' => 10,
                'brand' => 'Tecno',
                'range' => 'Pop',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Infinix
            [
                'name' => 'Infinix Hot 40 Pro',
                'description' => 'Infinix Hot 40 Pro avec écran 6.78" et 8GB RAM',
                'price' => 110000,
                'cost_price' => 85000,
                'stock_quantity' => 22,
                'min_stock_alert' => 5,
                'brand' => 'Infinix',
                'range' => 'Hot',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'Infinix Note 40',
                'description' => 'Infinix Note 40 avec charge rapide 70W',
                'price' => 135000,
                'cost_price' => 110000,
                'stock_quantity' => 15,
                'min_stock_alert' => 3,
                'brand' => 'Infinix',
                'range' => 'Note',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'Infinix Zero 30',
                'description' => 'Infinix Zero 30 avec caméra 108MP',
                'price' => 160000,
                'cost_price' => 130000,
                'stock_quantity' => 12,
                'min_stock_alert' => 2,
                'brand' => 'Infinix',
                'range' => 'Zero',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'Infinix Smart 8',
                'description' => 'Infinix Smart 8 avec batterie 5000mAh',
                'price' => 65000,
                'cost_price' => 50000,
                'stock_quantity' => 30,
                'min_stock_alert' => 8,
                'brand' => 'Infinix',
                'range' => 'Smart',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Itel
            [
                'name' => 'Itel A70',
                'description' => 'Itel A70 avec écran 6.6" et 4GB RAM',
                'price' => 75000,
                'cost_price' => 60000,
                'stock_quantity' => 28,
                'min_stock_alert' => 7,
                'brand' => 'Itel',
                'range' => 'A-series',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Itel S23',
                'description' => 'Itel S23 avec caméra 50MP',
                'price' => 85000,
                'cost_price' => 65000,
                'stock_quantity' => 20,
                'min_stock_alert' => 5,
                'brand' => 'Itel',
                'range' => 'S-series',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Samsung
            [
                'name' => 'Samsung Galaxy A54',
                'description' => 'Samsung Galaxy A54 avec écran Super AMOLED 6.4"',
                'price' => 220000,
                'cost_price' => 180000,
                'stock_quantity' => 15,
                'min_stock_alert' => 3,
                'brand' => 'Samsung',
                'range' => 'Galaxy A',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'Samsung Galaxy M34',
                'description' => 'Samsung Galaxy M34 avec batterie 6000mAh',
                'price' => 180000,
                'cost_price' => 150000,
                'stock_quantity' => 18,
                'min_stock_alert' => 4,
                'brand' => 'Samsung',
                'range' => 'Galaxy M',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'Samsung Galaxy S24',
                'description' => 'Samsung Galaxy S24 avec IA intégrée',
                'price' => 450000,
                'cost_price' => 380000,
                'stock_quantity' => 8,
                'min_stock_alert' => 2,
                'brand' => 'Samsung',
                'range' => 'Galaxy S',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],

            // iPhone
            [
                'name' => 'iPhone 15 Pro',
                'description' => 'iPhone 15 Pro avec puce A17 Pro et caméra 48MP',
                'price' => 850000,
                'cost_price' => 700000,
                'stock_quantity' => 12,
                'min_stock_alert' => 2,
                'brand' => 'iPhone',
                'range' => 'iPhone 15',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'iPhone 14',
                'description' => 'iPhone 14 avec puce A15 Bionic',
                'price' => 650000,
                'cost_price' => 550000,
                'stock_quantity' => 20,
                'min_stock_alert' => 3,
                'brand' => 'iPhone',
                'range' => 'iPhone 14',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'iPhone 13',
                'description' => 'iPhone 13 avec écran Super Retina XDR',
                'price' => 550000,
                'cost_price' => 450000,
                'stock_quantity' => 25,
                'min_stock_alert' => 5,
                'brand' => 'iPhone',
                'range' => 'iPhone 13',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Xiaomi / Redmi
            [
                'name' => 'Redmi Note 13 Pro',
                'description' => 'Redmi Note 13 Pro avec charge rapide 120W',
                'price' => 175000,
                'cost_price' => 140000,
                'stock_quantity' => 16,
                'min_stock_alert' => 3,
                'brand' => 'Xiaomi',
                'range' => 'Redmi Note',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'Redmi A3',
                'description' => 'Redmi A3 entrée de gamme avec Android Go',
                'price' => 60000,
                'cost_price' => 45000,
                'stock_quantity' => 40,
                'min_stock_alert' => 10,
                'brand' => 'Xiaomi',
                'range' => 'Redmi A',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Poco X6 Pro',
                'description' => 'Poco X6 Pro avec processeur MediaTek Dimensity 8300',
                'price' => 195000,
                'cost_price' => 160000,
                'stock_quantity' => 14,
                'min_stock_alert' => 3,
                'brand' => 'Xiaomi',
                'range' => 'Poco X',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],

            // Oppo
            [
                'name' => 'Oppo A78',
                'description' => 'Oppo A78 avec charge rapide 67W',
                'price' => 145000,
                'cost_price' => 120000,
                'stock_quantity' => 17,
                'min_stock_alert' => 4,
                'brand' => 'Oppo',
                'range' => 'A-series',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Oppo Reno 11',
                'description' => 'Oppo Reno 11 avec caméra 50MP',
                'price' => 280000,
                'cost_price' => 230000,
                'stock_quantity' => 10,
                'min_stock_alert' => 2,
                'brand' => 'Oppo',
                'range' => 'Reno',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],

            // Huawei
            [
                'name' => 'Huawei Nova 12',
                'description' => 'Huawei Nova 12 avec écran OLED',
                'price' => 240000,
                'cost_price' => 200000,
                'stock_quantity' => 12,
                'min_stock_alert' => 2,
                'brand' => 'Huawei',
                'range' => 'Nova',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],

            // Téléphones à touches
            [
                'name' => 'Nokia 105',
                'description' => 'Téléphone à touches Nokia 105 avec batterie longue durée',
                'price' => 25000,
                'cost_price' => 18000,
                'stock_quantity' => 50,
                'min_stock_alert' => 15,
                'brand' => 'Nokia',
                'range' => 'C-series',
                'format' => 'à touches',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Itel T531',
                'description' => 'Téléphone à touches Itel T531',
                'price' => 20000,
                'cost_price' => 15000,
                'stock_quantity' => 45,
                'min_stock_alert' => 12,
                'brand' => 'Itel',
                'range' => 'A-series',
                'format' => 'à touches',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Vivo
            [
                'name' => 'Vivo Y100',
                'description' => 'Vivo Y100 avec écran AMOLED et charge rapide',
                'price' => 165000,
                'cost_price' => 135000,
                'stock_quantity' => 14,
                'min_stock_alert' => 3,
                'brand' => 'Vivo',
                'range' => 'Y-series',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'Vivo V29',
                'description' => 'Vivo V29 avec caméra 50MP et écran 6.78"',
                'price' => 295000,
                'cost_price' => 240000,
                'stock_quantity' => 9,
                'min_stock_alert' => 2,
                'brand' => 'Vivo',
                'range' => 'V-series',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],

            // Realme
            [
                'name' => 'Realme C55',
                'description' => 'Realme C55 avec charge rapide 33W',
                'price' => 115000,
                'cost_price' => 90000,
                'stock_quantity' => 20,
                'min_stock_alert' => 5,
                'brand' => 'Realme',
                'range' => 'C-series',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Realme Narzo 70',
                'description' => 'Realme Narzo 70 avec processeur MediaTek',
                'price' => 140000,
                'cost_price' => 115000,
                'stock_quantity' => 16,
                'min_stock_alert' => 4,
                'brand' => 'Realme',
                'range' => 'Narzo',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // OnePlus
            [
                'name' => 'OnePlus Nord 3',
                'description' => 'OnePlus Nord 3 avec écran 120Hz',
                'price' => 320000,
                'cost_price' => 270000,
                'stock_quantity' => 11,
                'min_stock_alert' => 2,
                'brand' => 'OnePlus',
                'range' => 'Nord',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],

            // Motorola
            [
                'name' => 'Motorola Moto G84',
                'description' => 'Motorola Moto G84 avec écran pOLED',
                'price' => 185000,
                'cost_price' => 150000,
                'stock_quantity' => 13,
                'min_stock_alert' => 3,
                'brand' => 'Motorola',
                'range' => 'Moto G',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Honor
            [
                'name' => 'Honor 90',
                'description' => 'Honor 90 avec caméra 200MP',
                'price' => 260000,
                'cost_price' => 220000,
                'stock_quantity' => 10,
                'min_stock_alert' => 2,
                'brand' => 'Honor',
                'range' => 'Magic',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],

            // Google Pixel
            [
                'name' => 'Google Pixel 8',
                'description' => 'Google Pixel 8 avec Android pur et IA',
                'price' => 480000,
                'cost_price' => 400000,
                'stock_quantity' => 7,
                'min_stock_alert' => 2,
                'brand' => 'Google Pixel',
                'range' => 'Pixel 8',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'Google Pixel 7a',
                'description' => 'Google Pixel 7a avec caméra 64MP',
                'price' => 350000,
                'cost_price' => 290000,
                'stock_quantity' => 9,
                'min_stock_alert' => 2,
                'brand' => 'Google Pixel',
                'range' => 'Pixel 7',
                'format' => 'tactile',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Tablettes
            [
                'name' => 'Samsung Galaxy Tab A9',
                'description' => 'Tablette Android Samsung Galaxy Tab A9 10.5"',
                'price' => 180000,
                'cost_price' => 150000,
                'stock_quantity' => 12,
                'min_stock_alert' => 3,
                'brand' => 'Samsung',
                'range' => 'Galaxy Tab',
                'format' => 'tablette Android',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Lenovo Tab M10',
                'description' => 'Tablette Android Lenovo Tab M10 10.1"',
                'price' => 120000,
                'cost_price' => 95000,
                'stock_quantity' => 15,
                'min_stock_alert' => 4,
                'brand' => 'Lenovo',
                'range' => 'Tab M',
                'format' => 'tablette Android',
                'category_id' => $phoneCategory->id,
                'product_type_id' => $phoneType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
        ];

        // ============================================
        // PRODUITS ACCESSOIRES
        // ============================================
        $accessories = [
            // Chargeurs
            [
                'name' => 'Chargeur mural USB-C rapide 25W',
                'description' => 'Chargeur mural USB-C avec charge rapide 25W pour smartphones',
                'price' => 8000,
                'cost_price' => 5000,
                'stock_quantity' => 60,
                'min_stock_alert' => 15,
                'type_accessory' => 'Chargeur mural',
                'compatibility' => 'Type-C universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Chargeur mural iPhone Lightning',
                'description' => 'Chargeur mural Apple Lightning 20W pour iPhone',
                'price' => 12000,
                'cost_price' => 8000,
                'stock_quantity' => 40,
                'min_stock_alert' => 10,
                'type_accessory' => 'Chargeur mural',
                'compatibility' => 'iPhone (Lightning)',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Chargeur mural Micro-USB',
                'description' => 'Chargeur mural Micro-USB 2A pour anciens smartphones',
                'price' => 5000,
                'cost_price' => 3000,
                'stock_quantity' => 50,
                'min_stock_alert' => 12,
                'type_accessory' => 'Chargeur mural',
                'compatibility' => 'Micro-USB universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Câbles
            [
                'name' => 'Câble USB Type-C 2m',
                'description' => 'Câble USB Type-C 2 mètres pour charge et transfert de données',
                'price' => 6000,
                'cost_price' => 3500,
                'stock_quantity' => 80,
                'min_stock_alert' => 20,
                'type_accessory' => 'Câble USB',
                'compatibility' => 'Type-C universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Câble Lightning iPhone 1m',
                'description' => 'Câble Lightning Apple original 1 mètre',
                'price' => 10000,
                'cost_price' => 6000,
                'stock_quantity' => 55,
                'min_stock_alert' => 15,
                'type_accessory' => 'Câble USB',
                'compatibility' => 'iPhone (Lightning)',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Câble Micro-USB 1.5m',
                'description' => 'Câble Micro-USB 1.5 mètres',
                'price' => 4000,
                'cost_price' => 2500,
                'stock_quantity' => 70,
                'min_stock_alert' => 18,
                'type_accessory' => 'Câble USB',
                'compatibility' => 'Micro-USB universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Power Banks
            [
                'name' => 'Batterie externe 10000mAh',
                'description' => 'Power Bank 10000mAh avec charge rapide USB-C',
                'price' => 25000,
                'cost_price' => 15000,
                'stock_quantity' => 35,
                'min_stock_alert' => 8,
                'type_accessory' => 'Batterie externe (Power Bank)',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'Batterie externe 20000mAh',
                'description' => 'Power Bank 20000mAh double port USB',
                'price' => 35000,
                'cost_price' => 22000,
                'stock_quantity' => 25,
                'min_stock_alert' => 5,
                'type_accessory' => 'Batterie externe (Power Bank)',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => true,
            ],

            // Écouteurs
            [
                'name' => 'Écouteurs filaires avec micro',
                'description' => 'Écouteurs filaires avec micro et contrôle volume',
                'price' => 5000,
                'cost_price' => 3000,
                'stock_quantity' => 90,
                'min_stock_alert' => 25,
                'type_accessory' => 'Écouteurs filaires',
                'compatibility' => 'Casques jack 3.5 mm',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Écouteurs Bluetooth TWS',
                'description' => 'Écouteurs Bluetooth True Wireless avec boîtier de charge',
                'price' => 18000,
                'cost_price' => 12000,
                'stock_quantity' => 45,
                'min_stock_alert' => 10,
                'type_accessory' => 'Écouteurs Bluetooth',
                'compatibility' => 'Accessoires audio Bluetooth 5.0',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => true,
            ],

            // Coques
            [
                'name' => 'Coque de protection silicone',
                'description' => 'Coque de protection en silicone souple',
                'price' => 3000,
                'cost_price' => 1500,
                'stock_quantity' => 100,
                'min_stock_alert' => 30,
                'type_accessory' => 'Coque de protection',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Coque iPhone 14/15',
                'description' => 'Coque de protection pour iPhone 14 et 15',
                'price' => 5000,
                'cost_price' => 2500,
                'stock_quantity' => 40,
                'min_stock_alert' => 10,
                'type_accessory' => 'Coque de protection',
                'compatibility' => 'iPhone 11 à 15',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Films protecteurs
            [
                'name' => 'Film protecteur verre trempé',
                'description' => 'Film protecteur en verre trempé 9H',
                'price' => 4000,
                'cost_price' => 2000,
                'stock_quantity' => 85,
                'min_stock_alert' => 20,
                'type_accessory' => 'Film protecteur (verre trempé)',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Film protecteur iPhone',
                'description' => 'Film protecteur verre trempé pour iPhone',
                'price' => 6000,
                'cost_price' => 3000,
                'stock_quantity' => 50,
                'min_stock_alert' => 12,
                'type_accessory' => 'Film protecteur (verre trempé)',
                'compatibility' => 'iPhone 11 à 15',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Supports
            [
                'name' => 'Support téléphone voiture magnétique',
                'description' => 'Support magnétique pour téléphone en voiture',
                'price' => 8000,
                'cost_price' => 5000,
                'stock_quantity' => 30,
                'min_stock_alert' => 8,
                'type_accessory' => 'Support téléphone voiture',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Support bureau pliable',
                'description' => 'Support réglable pour téléphone sur bureau',
                'price' => 7000,
                'cost_price' => 4000,
                'stock_quantity' => 35,
                'min_stock_alert' => 9,
                'type_accessory' => 'Support bureau pliable',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Autres accessoires
            [
                'name' => 'Carte mémoire microSD 64GB',
                'description' => 'Carte mémoire microSD 64GB classe 10',
                'price' => 12000,
                'cost_price' => 8000,
                'stock_quantity' => 40,
                'min_stock_alert' => 10,
                'type_accessory' => 'Carte mémoire (SD / microSD)',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Adaptateur OTG USB-C',
                'description' => 'Adaptateur OTG USB-C vers USB-A',
                'price' => 5000,
                'cost_price' => 3000,
                'stock_quantity' => 45,
                'min_stock_alert' => 12,
                'type_accessory' => 'Clé USB OTG',
                'compatibility' => 'Type-C universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Haut-parleur Bluetooth portable',
                'description' => 'Haut-parleur Bluetooth avec batterie intégrée',
                'price' => 22000,
                'cost_price' => 15000,
                'stock_quantity' => 25,
                'min_stock_alert' => 6,
                'type_accessory' => 'Haut-parleur Bluetooth',
                'compatibility' => 'Accessoires audio Bluetooth 5.0',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => true,
            ],

            // Plus de chargeurs
            [
                'name' => 'Chargeur rapide PD 30W',
                'description' => 'Chargeur Power Delivery 30W pour smartphones rapides',
                'price' => 15000,
                'cost_price' => 9000,
                'stock_quantity' => 30,
                'min_stock_alert' => 8,
                'type_accessory' => 'Chargeur mural',
                'compatibility' => 'Type-C universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Chargeur voiture USB-C',
                'description' => 'Chargeur allume-cigare USB-C pour voiture',
                'price' => 7000,
                'cost_price' => 4000,
                'stock_quantity' => 40,
                'min_stock_alert' => 10,
                'type_accessory' => 'Chargeur allume-cigare',
                'compatibility' => 'Type-C universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Station de charge sans fil',
                'description' => 'Station de charge sans fil Qi 15W',
                'price' => 28000,
                'cost_price' => 18000,
                'stock_quantity' => 20,
                'min_stock_alert' => 5,
                'type_accessory' => 'Station de charge sans fil',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => true,
            ],

            // Plus de câbles
            [
                'name' => 'Câble USB-C vers Lightning',
                'description' => 'Câble USB-C vers Lightning pour iPhone',
                'price' => 12000,
                'cost_price' => 7000,
                'stock_quantity' => 35,
                'min_stock_alert' => 9,
                'type_accessory' => 'Câble USB',
                'compatibility' => 'iPhone (Lightning)',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Câble USB-C 3m',
                'description' => 'Câble USB-C 3 mètres pour charge longue distance',
                'price' => 8000,
                'cost_price' => 5000,
                'stock_quantity' => 50,
                'min_stock_alert' => 12,
                'type_accessory' => 'Câble USB',
                'compatibility' => 'Type-C universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Adaptateur Type-C / Micro USB',
                'description' => 'Adaptateur Type-C vers Micro-USB',
                'price' => 3000,
                'cost_price' => 1500,
                'stock_quantity' => 60,
                'min_stock_alert' => 15,
                'type_accessory' => 'Adaptateur Type-C / Micro USB',
                'compatibility' => 'Micro-USB universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Casques
            [
                'name' => 'Casque audio circum-aural',
                'description' => 'Casque audio over-ear avec micro',
                'price' => 25000,
                'cost_price' => 16000,
                'stock_quantity' => 22,
                'min_stock_alert' => 6,
                'type_accessory' => 'Casque audio',
                'compatibility' => 'Casques jack 3.5 mm',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Casque Bluetooth avec réduction de bruit',
                'description' => 'Casque Bluetooth avec ANC et autonomie 30h',
                'price' => 35000,
                'cost_price' => 24000,
                'stock_quantity' => 18,
                'min_stock_alert' => 4,
                'type_accessory' => 'Casque audio',
                'compatibility' => 'Accessoires audio Bluetooth 5.0',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => true,
            ],

            // Supports et trépieds
            [
                'name' => 'Trépied photo / selfie stick',
                'description' => 'Trépied télescopique pour selfies et photos',
                'price' => 10000,
                'cost_price' => 6000,
                'stock_quantity' => 28,
                'min_stock_alert' => 7,
                'type_accessory' => 'Trépied photo / selfie stick',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Support magnétique voiture',
                'description' => 'Support magnétique pour tableau de bord voiture',
                'price' => 9000,
                'cost_price' => 5500,
                'stock_quantity' => 32,
                'min_stock_alert' => 8,
                'type_accessory' => 'Support téléphone voiture',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],

            // Accessoires spécifiques
            [
                'name' => 'Étui tablette avec clavier',
                'description' => 'Étui tablette avec clavier Bluetooth intégré',
                'price' => 32000,
                'cost_price' => 22000,
                'stock_quantity' => 15,
                'min_stock_alert' => 4,
                'type_accessory' => 'Étui tablette',
                'compatibility' => 'Tablettes Android 10"',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Hub USB 4 ports',
                'description' => 'Hub USB avec 4 ports pour tablettes et smartphones',
                'price' => 15000,
                'cost_price' => 9000,
                'stock_quantity' => 25,
                'min_stock_alert' => 6,
                'type_accessory' => 'Hub USB',
                'compatibility' => 'Type-C universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Dock de recharge multiple',
                'description' => 'Dock de recharge pour 3 appareils simultanés',
                'price' => 25000,
                'cost_price' => 16000,
                'stock_quantity' => 20,
                'min_stock_alert' => 5,
                'type_accessory' => 'Dock de recharge multiple',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'name' => 'Carte mémoire microSD 128GB',
                'description' => 'Carte mémoire microSD 128GB classe 10',
                'price' => 18000,
                'cost_price' => 12000,
                'stock_quantity' => 35,
                'min_stock_alert' => 9,
                'type_accessory' => 'Carte mémoire (SD / microSD)',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Adaptateur SIM / Ejecteur SIM',
                'description' => 'Kit adaptateur SIM et outil d\'éjection',
                'price' => 2000,
                'cost_price' => 1000,
                'stock_quantity' => 80,
                'min_stock_alert' => 20,
                'type_accessory' => 'Adaptateur SIM / Ejecteur SIM',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Connecteur magnétique USB-C',
                'description' => 'Connecteur magnétique USB-C pour charge facile',
                'price' => 6000,
                'cost_price' => 3500,
                'stock_quantity' => 38,
                'min_stock_alert' => 10,
                'type_accessory' => 'Connecteur magnétique',
                'compatibility' => 'Type-C universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Câble auxiliaire audio 3.5mm',
                'description' => 'Câble auxiliaire audio jack 3.5mm 1.5m',
                'price' => 4000,
                'cost_price' => 2500,
                'stock_quantity' => 55,
                'min_stock_alert' => 14,
                'type_accessory' => 'Câble auxiliaire audio (jack 3.5 mm)',
                'compatibility' => 'Casques jack 3.5 mm',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Mini ventilateur USB',
                'description' => 'Mini ventilateur USB pour refroidir smartphone',
                'price' => 5000,
                'cost_price' => 3000,
                'stock_quantity' => 42,
                'min_stock_alert' => 11,
                'type_accessory' => 'Mini ventilateur USB',
                'compatibility' => 'USB universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'name' => 'Anneau lumineux Ring Light',
                'description' => 'Anneau lumineux LED pour selfies et vidéos',
                'price' => 12000,
                'cost_price' => 7000,
                'stock_quantity' => 30,
                'min_stock_alert' => 8,
                'type_accessory' => 'Anneau lumineux (Ring Light)',
                'compatibility' => 'Android universel',
                'category_id' => $accessoryCategory->id,
                'product_type_id' => $accessoryType->id,
                'status' => 'active',
                'is_featured' => false,
            ],
        ];

        // Créer tous les produits
        $allProducts = array_merge($phones, $accessories);
        $created = 0;

        foreach ($allProducts as $productData) {
            try {
                // Générer SKU et slug automatiquement
                $sku = $productData['sku'] ?? 'SKU-' . strtoupper(Str::random(8));
                $slug = Product::generateSlug($productData['name']);

                $product = Product::create([
                    'name' => $productData['name'],
                    'slug' => $slug,
                    'description' => $productData['description'] ?? '',
                    'price' => $productData['price'],
                    'cost_price' => $productData['cost_price'],
                    'stock_quantity' => $productData['stock_quantity'],
                    'min_stock_alert' => $productData['min_stock_alert'],
                    'category_id' => $productData['category_id'],
                    'product_type_id' => $productData['product_type_id'],
                    'sku' => $sku,
                    'barcode' => 'BC-' . strtoupper(Str::random(10)),
                    'brand' => $productData['brand'] ?? null,
                    'range' => $productData['range'] ?? null,
                    'format' => $productData['format'] ?? null,
                    'type_accessory' => $productData['type_accessory'] ?? null,
                    'compatibility' => $productData['compatibility'] ?? null,
                    'status' => $productData['status'] ?? 'active',
                    'is_featured' => $productData['is_featured'] ?? false,
                    'meta_title' => $productData['name'],
                    'meta_description' => $productData['description'] ?? '',
                    'tags' => [],
                    'images' => [],
                ]);

                $created++;
            } catch (\Exception $e) {
                $this->command->error("❌ Erreur création produit {$productData['name']}: " . $e->getMessage());
            }
        }

        $this->command->info("✅ {$created} produits créés avec succès !");
        $this->command->info("📱 Téléphones: " . count($phones));
        $this->command->info("🔌 Accessoires: " . count($accessories));
    }
}
